## YAML Template.
---
form:
    attributes:
        id: amplify_add_album_form
    ajax:
        url: ajax/entity/create
        success: user/profile
    fields:
        #this is a staple for system stability        
        album_artist_id: 
            attributes:
                name: album_artist_id
                id: album_artist_id
                type: hidden
                placeholder: Album Artist ID
                label: 
                value:
                    source: session
                    target: artist_id
        album_name: 
            attributes:
                name: album_name
                id: album_name
                type: string
                placeholder: Album Name
                value:
                required: true
        album_art: 
            attributes:
                name: album_art
                id: album_art
                type: file
                placeholder: Album Art
                remove_uploader: false
                required: true
        album_release_date: 
            attributes:
                name: album_release_date
                id: album_release_date
                type: date
                placeholder: Release Date
        album_artist: 
            attributes:
                name: album_artist
                id: album_artist
                type: string
                placeholder: Album Artist
                note: for compilations, labels, etc.
        album_description: 
            attributes:
                name: album_description
                id: album_description
                type: textarea
                placeholder: About The Album
        album_credits: 
            attributes:
                name: album_credits
                id: album_credits
                type: textarea
                placeholder: Album Credits        
        album_tags: 
            attributes:
                name: album_tags
                id: album_tags
                type: string
                placeholder: Album Tags        
        album_status: 
            attributes:
                name: album_status
                id: album_status
                type: enumeration
                enumeration_type: radio
                options: Draft, Published
                placeholder:
        entity:
            attributes:
                type: hidden
                name: entity
                id: entity
                value: artist
        csrf_token:
            attributes:
                type: csrf
                name: csrf_token
        error-container: message
    submit:
        label: Add Album
        id: next
        class: full-width,ladda-button
        span_class: ladda-label
        data_controls:
            data-style: slide-up
