## YAML Template
## Blog Template
theme: default
page_title: Blog &raquo; Home
body_id: home
login_required: false
is_admin: false
data:
page:  
    css:
    js:    
    layout: main
    header:
        partials:
            blog/frontend/header
    body:
        partials:
            blog/frontend/sidebar
            blog/frontend/content
    footer:
        partials:
            blog/frontend/footer:
