## YAML Template.
## Were using the default for LenovoPH
theme: default
page_title: Amplify &raquo; Home
body_id: amplify-home
login_required: false
data:
    forms:
        login_form
page:  
    css:
    js:    
    layout: main
    
    header:
        
    body:
        partials:
            open_div:
                class: page-wrap
            header:
                text: Log on to your Account
            login_form:
            close_div:
            clearfix:
    footer:
        partials:
            bare_navigation:
            copyright:
                #todo make this dynamic for change of years
                company: Amplify PH.
