## YAML Template.
## Were using the default for LenovoPH
theme: default
page_title: Amplify &raquo; Artist Signup
body_id: amplify-signup
login_required: false
data:
    forms:
        register_last_form
page:  
    css:
    js:    
    layout: main
    
    header:
        
    body:
        partials:
            open_div:
                class: page-wrap
            welcome:
                welcome_message: ', Welcome to Amplify.ph'
                welcome_source: session
                welcome_value: artist_band_name
            register_last_form:
            close_div:
            clearfix:
    footer:
        partials:
            bare_navigation:
            copyright:
                #todo make this dynamic for change of years
                company: Amplify PH.
